spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create

decorator:
  datasource:
    p6spy:
      enable-logging: true

aws:
  access-key: ${IAM_ACCESS_KEY}
  secret-key: ${IAM_SECRET_KEY}
  region: ${AWS_REGION}
  bucket-name: ${BUCKET_NAME}


cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false

mod: server

logTracer: true